// 중요한 키워드를 오타나지 않게 확인하기 위한 상수 생성
export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'
export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'